- name: Install HAProxy
  ansible.builtin.yum:
    name: haproxy
    state: present

- name: Deploy HAProxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify: Restart HAProxy

- name: Enable and start HAProxy service
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: yes

- name: Enable HTTPD network connect SELinux boolean
  ansible.builtin.command: setsebool -P httpd_can_network_connect 1
  become: yes
