- name: Install Apache
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Ensure Apache service is started and enabled
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: Create web root directory
  ansible.builtin.file:
    path: /opt/html
    state: directory
    owner: apache
    group: apache
    mode: '0755'

- name: Deploy index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /opt/html/index.html
    owner: apache
    group: apache
    mode: '0644'

- name: Configure Apache to serve /opt/html
  ansible.builtin.copy:
    dest: /etc/httpd/conf.d/custom.conf
    content: |
      <VirtualHost *:80>
          DocumentRoot "/opt/html"
          <Directory "/opt/html">
              Require all granted
          </Directory>
      </VirtualHost>
    owner: apache
    group: apache
    mode: '0644'
  notify: Restart Apache

  - name: Enable HTTPD network connect SELinux boolean
  ansible.builtin.command: setsebool -P httpd_can_network_connect 1
  become: yes

